# Generated by Django 4.0.3 on 2022-06-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '__first__'),
        ('park', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('depar_time', models.TextField()),
                ('arrival_time', models.TextField()),
                ('price', models.IntegerField()),
                ('degree_of_comf', models.CharField(max_length=100)),
                ('num_of_custom', models.IntegerField()),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.fleet')),
                ('num_seat', models.ManyToManyField(to='control.seat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.trip')),
            ],
        ),
    ]
