# Generated by Django 4.0.3 on 2022-06-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_control_trip_alter_seat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.TextField(default='off'),
            preserve_default=False,
        ),
    ]
