# Generated by Django 4.0.3 on 2022-06-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_seat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='name',
        ),
        migrations.RemoveField(
            model_name='control',
            name='price',
        ),
    ]
