# Generated by Django 4.0.3 on 2022-05-22 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('mileage', models.IntegerField()),
                ('num_of_flights_perform', models.IntegerField()),
                ('date_of_next', models.DateField()),
                ('date_of_last', models.DateField()),
                ('current_flight', models.CharField(max_length=100)),
                ('driver_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_1', to='drivers.driver')),
                ('driver_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_2', to='drivers.driver')),
            ],
            options={
                'unique_together': {('driver_1', 'driver_2')},
            },
        ),
    ]
