# Generated by Django 4.0.3 on 2022-05-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fleet',
            unique_together=set(),
        ),
    ]
