# Generated by Django 4.0.3 on 2022-05-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_name'),
        ('park', '0002_alter_fleet_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='route',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
            preserve_default=False,
        ),
    ]
