# Generated by Django 4.0.3 on 2022-05-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_fleet_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='photo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
