# Generated by Django 4.0.3 on 2022-05-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_fleet_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='photo',
        ),
    ]
