# Generated by Django 4.0.3 on 2022-06-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='occupancy',
        ),
    ]
