# Generated by Django 4.0.3 on 2022-05-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='photo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
