# Generated by Django 4.0.3 on 2022-05-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_trip_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
