# Generated by Django 4.0.3 on 2022-05-22 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('park', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_seat', models.IntegerField()),
                ('contact_info', models.CharField(max_length=100)),
                ('depar_time', models.DateField()),
                ('arrival_time', models.DateField()),
                ('price', models.IntegerField()),
                ('degree_of_comf', models.CharField(max_length=100)),
                ('num_of_custom', models.IntegerField()),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.fleet')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.trip')),
            ],
        ),
    ]
