# Generated by Django 4.0.3 on 2022-06-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=100)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.control')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.seat')),
            ],
        ),
    ]
