# Generated by Django 4.0.3 on 2022-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_name',
            field=models.CharField(default='NAME', max_length=100),
            preserve_default=False,
        ),
    ]
