# Generated by Django 4.0.3 on 2022-05-22 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_of_seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('num_of_fines', models.IntegerField()),
                ('num_of_flights', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('degree_of_cong', models.CharField(max_length=100)),
                ('degree_of_reliab', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.bus')),
            ],
        ),
    ]
